name: Build and push dlcs-varnish docker image

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build-push-varnish:
    runs-on: ubuntu-latest
    needs: test-dotnet
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-build-and-push
        name: build and push
        with:
          image-name: "dlcs-varnish"
          dockerfile: "Dockerfile"
          context: "."
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-push-thumbs:
    runs-on: ubuntu-latest
    needs: test-dotnet
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-build-and-push
        with:
          image-name: "dlcs-varnish-cleanup"
          dockerfile: "Dockerfile"
          context: "./varnish-cleanup"
          github-token: ${{ secrets.GITHUB_TOKEN }}
